### ISSUE TITLE
class org.springframework.boot.actuate.endpoint.mvc.MvcEndpoint not found in spring boot 2.7.1

### ISSUE THREAD

**Issue by iamcaoxudong** [taboola/async-profiler-actuator-endpoint#12]
**When used latest version 2.0.1_2.8.3 with Spring Boot 2.7.1, the following error is reported. A closer look reveals that the missing class  org.springframework.boot.actuate.endpoint.mvc.MvcEndpoint has been removed in Spring boot 2.7.1:**

![image](https://user-images.githubusercontent.com/50730962/182067127-67b0b739-6b90-40ed-871b-2132a57674bc.png)

**Comment by Shahar-l-Taboola** [comment]
Thanks @iamcaoxudong , 
This was resolved with
https://github.com/taboola/async-profiler-actuator-endpoint/pull/22
